# Generated by Django 3.2 on 2021-04-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0013_auto_20200611_2207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='genre',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='movie_logo',
            new_name='location_logo',
        ),
        migrations.RenameField(
            model_name='mylist',
            old_name='watch',
            new_name='Visited',
        ),
        migrations.RenameField(
            model_name='mylist',
            old_name='movie',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='myrating',
            old_name='movie',
            new_name='location',
        ),
    ]
